# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Node.js-v4-(or-io.js-v3)-compiler-requirements
dist: trusty
sudo: false
language: node_js
node_js:
  - "6.9.1"
cache:
  directories:
    - node_modules
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
